// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgafluaswmlrcarzamue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nYWZsdWFzd21scmNhcnphbXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjUwMTIsImV4cCI6MjA2NTAwMTAxMn0.61z-68C4A5XiO3x6az-CM1qwb77jKufgY2Q4zFbuvl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);